// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/openai-accounts-cli/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetByID(ctx context.Context, id domain.AccountID) (domain.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AccountID) (domain.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AccountID) domain.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AccountID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.AccountID
func (_e *MockAccountRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAccountRepository_GetByID_Call {
	return &MockAccountRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAccountRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.AccountID)) *MockAccountRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AccountID
		if args[1] != nil {
			arg1 = args[1].(domain.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) Return(account domain.Account, err error) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.AccountID) (domain.Account, error)) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) List(ctx context.Context) ([]domain.Account, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Account, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Account); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAccountRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountRepository_Expecter) List(ctx interface{}) *MockAccountRepository_List_Call {
	return &MockAccountRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAccountRepository_List_Call) Run(run func(ctx context.Context)) *MockAccountRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_List_Call) Return(accounts []domain.Account, err error) *MockAccountRepository_List_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Account, error)) *MockAccountRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Save(ctx context.Context, account domain.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccountRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - account domain.Account
func (_e *MockAccountRepository_Expecter) Save(ctx interface{}, account interface{}) *MockAccountRepository_Save_Call {
	return &MockAccountRepository_Save_Call{Call: _e.mock.On("Save", ctx, account)}
}

func (_c *MockAccountRepository_Save_Call) Run(run func(ctx context.Context, account domain.Account)) *MockAccountRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Account
		if args[1] != nil {
			arg1 = args[1].(domain.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Save_Call) Return(err error) *MockAccountRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Save_Call) RunAndReturn(run func(ctx context.Context, account domain.Account) error) *MockAccountRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
